[package]
name = "EscapeGBS"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.10" #rocket webframework
rand = "0.8.0" #random
chrono = "0.4" #time